server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://47.107.139.152:3306/auth?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
    schema: classpath:/schema.sql
    #第一次启动做建表用，之后注释掉
#    initialization-mode: always
mybatis:
  config-location: classpath:/mybatis-config.xml