server:
  port: 8668

spring:
  datasource:
    #    username: root
    #    password: 123456
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://47.107.139.152:3306/supermall?serverTimezone=CTT
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.107.139.152:3306/supermall?serverTimezone=CTT
      username: root
      password: 123456
      initial-size: 1 # 初始化大小
      min-idle: 1 # 最小
      max-active: 20  # 最大
      max-wait: 60000 # 获取连接超时时间
      time-between-eviction-runs-millis: 60000 # 多久需要检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 30000 # 一个连接在池中最小的生存时间
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #监控统计拦截的filters
      filters: stat,wall
      aop-patterns: com.javayh.druid.*
      web-stat-filter:
        enabled: true #是否启用StatFilter默认值true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        # 是否启用statViewServlet配置
        enabled: true
        # 访问监控页面
        url-pattern: "/druid/*"
        # 禁止手动重置监控数据
        reset-enable: false
        # 设置监控页面的登陆名
        login-username: admin
        # 设置监控页面的登陆密码
        login-password: admin
  #    type: com.zaxxer.hikari.HikariDataSource
  #    hikari:
  #      minimum-idle: 5 #最小空闲连接数量
  #      maximum-pool-size: 15 #连连接池最大连接数，默认是10
  #      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为,默认值：true
  #      idle-timeout: 300000 #空闲连接存活最大时间，默认600000（10分钟）
  #      pool-name: MyHikariCP #连接池母子  DatebookHikariCP
  #      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
  #      connection-timeout: 15000 #数据库连接超时时间,默认30秒，即30000
  #      connection-test-query: SELECT 1
  redis:
    host: 47.107.139.152
    port: 6379
    password: redis
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 30
        min-idle: 0

mybatis-plus:
  # xml扫描，多个目录用逗号或者分号隔开隔开
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zxw.supermall.entity
#  global-config:
#    db-config:
#      table-underline: true
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#      insert-strategy: not_empty
#      id-type: auto


