


#============================================================================
# netty socket io setting
##============================================================================
## host在本地测试可以设置为localhost或者本机IP，在Linux服务器跑可换成服务器IP
#socketio.host=localhost
#socketio.port=9099
#  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
#socketio.maxFramePayloadLength=1048576
#  # 设置http交互最大内容长度
#socketio.maxHttpContentLength=1048576
#  # socket连接数大小（如只监听一个端口boss线程组为1即可）
#socketio.bossCount=1
#socketio.workCount=100
#socketio.allowCustomRequests=true
#  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
#socketio.upgradeTimeout=1000000
#  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
#socketio.pingTimeout=6000000
#  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
#socketio.pingInterval=25000

socketio:
  host: localhost
  port: 9099
  maxFramePayloadLength: 1048576
  maxHttpContentLength: 1048576
  bossCount: 4
  workCount: 100
  allowCustomRequests: true
  upgradeTimeout: 1000000
  pingTimeout: 6000000
  pingInterval: 25000

server:
  port: 9199
